export const categorias = [
  {
    id: 1,
    TituloDaCategoria: "Livros didáticos",
    ImgDaCategoria: "static/img/category/Didatic_books.png",
    AltImg: "Categoria -Família e Amizades",
  },
  {
    id: 2,
    TituloDaCategoria: "Livros paradidáticos",
    ImgDaCategoria: "static/img/category/Paradidatic_books.png",
    AltImg: "Livros de paradidáticos",
  },
  {
    id: 3,
    TituloDaCategoria: "Literatura clássica",
    ImgDaCategoria: "static/img/category/Classical_literature.png",
    AltImg: "Livros de literatura clássica",
  },
  {
    id: 4,
    TituloDaCategoria: "Literatura contemporânea",
    ImgDaCategoria: "static/img/category/Contemporary_literature.png",
    AltImg: "Livros de literatura contemporânea",
  },
  {
    id: 5,
    TituloDaCategoria: "Ciências Humanas e Sociais",
    ImgDaCategoria: "static/img/category/Human_and_Social_Sciences.png",
    AltImg: "Livros de ciências humanas e sociais",
  },
  {
    id: 6,
    TituloDaCategoria: "Tecnologia",
    ImgDaCategoria: "static/img/category/Technology.png",
    AltImg: "Livros de tecnologia",
  },
  {
    id: 7,
    TituloDaCategoria: "Informática",
    ImgDaCategoria: "static/img/category/Computing.png",
    AltImg: "Livros de informática",
  },
  {
    id: 8,
    TituloDaCategoria: "Dicionários e grámaticas",
    ImgDaCategoria: "static/img/category/Dictionaries_and_grammar_books.png",
    AltImg: "Livros de dicionários e gramáticas",
  },
  {
    id: 9,
    TituloDaCategoria: "Livros acadêmicos",
    ImgDaCategoria: "static/img/category/Academic_books.png",
    AltImg: "Livros acadêmicos",
  },

  {
    id: 10,
    TituloDaCategoria: "Literatura brasileira",
    ImgDaCategoria: "static/img/category/Literature.png",
    AltImg: "Livros de literatura brasileira",
  },
  {
    id: 11,
    TituloDaCategoria: "Literatura estrangeira",
    ImgDaCategoria: "static/img/category/Literature.png",
    AltImg: "Livros de literatura estrangeira",
  },
  {
    id: 12,
    TituloDaCategoria: "Romance",
    ImgDaCategoria: "static/img/category/Romance.png",
    AltImg: "Livros de romance",
  },
  {
    id: 13,
    TituloDaCategoria: "Ficção",
    ImgDaCategoria: "static/img/category/Fiction.png",
    AltImg: "Livros de ficção",
  },
  {
    id: 14,
    TituloDaCategoria: "Suspense",
    ImgDaCategoria: "static/img/category/Thriller.png",
    AltImg: "Livros de suspense",
  },
  {
    id: 15,
    TituloDaCategoria: "Fantásia",
    ImgDaCategoria: "static/img/category/Fantasy.png",
    AltImg: "Categoria -Família e Amizades",
  },
  {
    id: 16,
    TituloDaCategoria: "Terror",
    ImgDaCategoria: "static/img/category/Horror.png",
    AltImg: "Categoria -Família e Amizades",
  },
  {
    id: 17,
    TituloDaCategoria: "Drama",
    ImgDaCategoria: "static/img/category/Drama.png",
    AltImg: "Categoria -Família e Amizades",
  },
  {
    id: 18,
    TituloDaCategoria: "HQs e Mangás",
    ImgDaCategoria: "static/img/category/Comics_and_manga.png",
    AltImg: "Categoria -Família e Amizades",
  },
];
