export const categorias = [
  {
    id: 1,
    TituloDaCategoria: "Ficção",
    ImgDaCategoria: "static/img/category/Fiction.png",
    AltImg: "Categoria de Fiçção",
  },
  {
    id: 2,
    TituloDaCategoria: "Literatura brasileira",
    ImgDaCategoria: "static/img/category/Literature.png",
    AltImg: "Literatura brasileira",
  },
  {
    id: 3,
    TituloDaCategoria: "Literatura estrangeira",
    ImgDaCategoria: "static/img/category/Literature.png",
    AltImg: "Categoria -Família e Amizades",
  },
  {
    id: 4,
    TituloDaCategoria: "Romance",
    ImgDaCategoria: "static/img/category/Romance.png",
    AltImg: "Categoria -Família e Amizades",
  },
  {
    id: 5,
    TituloDaCategoria: "Suspense",
    ImgDaCategoria: "static/img/category/Thriller.png",
    AltImg: "Categoria -Família e Amizades",
  },
  {
    id: 6,
    TituloDaCategoria: "Mistério",
    ImgDaCategoria: "static/img/category/Mystery.png",
    AltImg: "Categoria -Família e Amizades",
  },
  {
    id: 7,
    TituloDaCategoria: "Fantásia",
    ImgDaCategoria: "static/img/category/Fantasy.png",
    AltImg: "Categoria -Família e Amizades",
  },
  {
    id: 8,
    TituloDaCategoria: "Terror",
    ImgDaCategoria: "static/img/category/Horror.png",
    AltImg: "Categoria -Família e Amizades",
  },
  {
    id: 9,
    TituloDaCategoria: "Drama",
    ImgDaCategoria: "static/img/category/Drama.png",
    AltImg: "Categoria -Família e Amizades",
  },
  {
    id: 10,
    TituloDaCategoria: "HQs e Mangás",
    ImgDaCategoria: "static/img/category/Comics_and_manga.png",
    AltImg: "Categoria -Família e Amizades",
  },
  {
    id: 11,
    TituloDaCategoria: "Livros didáticos",
    ImgDaCategoria: "static/img/category/Didatic_books.png",
    AltImg: "Categoria -Família e Amizades",
  },
  {
    id: 12,
    TituloDaCategoria: "Livros paradidáticos",
    ImgDaCategoria: "static/img/category/ficção.png",
    AltImg: "Categoria -Família e Amizades",
  },
  {
    id: 13,
    TituloDaCategoria: "Literatura clássica",
    ImgDaCategoria: "static/img/category/ficção.png",
    AltImg: "Categoria -Família e Amizades",
  },
  {
    id: 14,
    TituloDaCategoria: "Literatura contemporânea",
    ImgDaCategoria: "static/img/category/ficção.png",
    AltImg: "Categoria -Família e Amizades",
  },
  {
    id: 15,
    TituloDaCategoria: "Ciências Humanas e Sociais",
    ImgDaCategoria: "static/img/category/ficção.png",
    AltImg: "Categoria -Família e Amizades",
  },
  {
    id: 16,
    TituloDaCategoria: "Tecnologia",
    ImgDaCategoria: "static/img/category/ficção.png",
    AltImg: "Categoria -Família e Amizades",
  },
  {
    id: 17,
    TituloDaCategoria: "Informática",
    ImgDaCategoria: "static/img/category/ficção.png",
    AltImg: "Categoria -Família e Amizades",
  },
  {
    id: 18,
    TituloDaCategoria: "Dicionários e grámaticas",
    ImgDaCategoria: "static/img/category/ficção.png",
    AltImg: "Categoria -Família e Amizades",
  },
  {
    id: 19,
    TituloDaCategoria: "Livros acadêmicos",
    ImgDaCategoria: "static/img/category/ficção.png",
    AltImg: "Categoria -Família e Amizades",
  },
];
