export const promocoes = [
  {
    id: 1,
    imgCard: 'static/img/products/Euismod_anim.png',
    altImgCard: 'Euismod anim',
    nomeDoProduto: 'Euismod anim',
    precoPromocaoDoProduto: 'R$ 00,00',
    precoOriginalDoProduto: 'R$ 00,00',
  },
  {
    id: 2,
    imgCard: 'static/img/products/The_dolor_veniam.png',
    altImgCard: 'The dolor veniam',
    nomeDoProduto: 'The dolor veniam',
    precoPromocaoDoProduto: 'R$ 00,00',
    precoOriginalDoProduto: 'R$ 00,00',
  },
  {
    id: 3,
    imgCard: 'static/img/products/Animid_id_laborum.png',
    altImgCard: 'Animid id laborum',
    nomeDoProduto: 'Animid id laborum',
    precoPromocaoDoProduto: 'R$ 00,00',
    precoOriginalDoProduto: 'R$ 00,00',
  },
  {
    id: 4,
    imgCard: 'static/img/products/Mollit_elit.png',
    altImgCard: 'Mollit elit',
    nomeDoProduto: 'Mollit elit',
    precoPromocaoDoProduto: 'R$ 00,00',
    precoOriginalDoProduto: 'R$ 00,00',
  },
  {
    id: 5,
    imgCard: 'static/img/products/Laboris_nisi.png',
    altImgCard: 'Labiris nisi',
    nomeDoProduto: 'Labiris nisi',
    precoPromocaoDoProduto: 'R$ 00,00',
    precoOriginalDoProduto: 'R$ 00,00',
  },
  {
    id: 6,
    imgCard: 'static/img/products/Auto_irure_lorem.png',
    altImgCard: 'Auto irure lorem',
    nomeDoProduto: 'Auto irure lorem',
    precoPromocaoDoProduto: 'R$ 00,00',
    precoOriginalDoProduto: 'R$ 00,00',
  },
];
