export const promocoes = [
  {
    id: 1,
    imgCard: 'static/img/products/book.jpg',
    altImgCard: 'Ipsum Dolor Sit Amet',
    nomeDoProduto: 'Ipsum Dolor Sit Amet + Brinde exclusivo!',
    precoPromocaoDoProduto: 'R$ 00,00',
    precoOriginalDoProduto: 'R$ 00,00',
  },
  {
    id: 2,
    imgCard: 'static/img/products/book2.jpg',
    altImgCard: 'Lorem Ipsum',
    nomeDoProduto: 'Lorem Ipsum + Brinde exclusivo!',
    precoPromocaoDoProduto: 'R$ 00,00',
    precoOriginalDoProduto: 'R$ 00,00',
  },
  {
    id: 3,
    imgCard: 'static/img/products/book.jpg',
    altImgCard: 'Ipsum Dolor Sit Amet',
    nomeDoProduto: 'Ipsum Dolor Sit Amet + Brinde exclusivo!',
    precoPromocaoDoProduto: 'R$ 00,00',
    precoOriginalDoProduto: 'R$ 00,00',
  },
  {
    id: 4,
    imgCard: 'static/img/products/book2.jpg',
    altImgCard: 'Lorem Ipsum',
    nomeDoProduto: 'Lorem Ipsum + Brinde exclusivo!',
    precoPromocaoDoProduto: 'R$ 00,00',
    precoOriginalDoProduto: 'R$ 00,00',
  },
  {
    id: 5,
    imgCard: 'static/img/products/book.jpg',
    altImgCard: 'Ipsum Dolor Sit Amet',
    nomeDoProduto: 'Ipsum Dolor Sit Amet + Brinde exclusivo!',
    precoPromocaoDoProduto: 'R$ 00,00',
    precoOriginalDoProduto: 'R$ 00,00',
  },
  {
    id: 6,
    imgCard: 'static/img/products/book2.jpg',
    altImgCard: 'Lorem Ipsum',
    nomeDoProduto: 'Lorem Ipsum + Brinde exclusivo!',
    precoPromocaoDoProduto: 'R$ 00,00',
    precoOriginalDoProduto: 'R$ 00,00',
  },
];
